# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_foo', '0003_testmodelobj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='file',
        ),
    ]
